all:
	gcc -Wall -o server server.c
	gcc -Wall -o server1 server1.c
	gcc -Wall -o client client.c
	gcc -Wall -o tcpex tcpex.c
	gcc -Wall -o loc_client loc_client.c
	gcc -Wall -o loc_server loc_server.c
	gcc -Wall -o epoll_example epoll_example.c