all:
	gcc -Wall main.c -o main
	gcc -Wall main2.c -o main2
	gcc -Wall main3.c -o main3
	gcc -Wall main4.c -o main4
	gcc -Wall main5.c -o main5
	gcc -Wall main6.c -o main6

clean:
	rm main main2 main3 main4 main5 main6 || true